In [1]:
import numpy as np
# Activation functions
def relu(x): return np.maximum(0, x)
def relu_derivative(x): return (x > 0).astype(float)

def tanh(x): return np.tanh(x)
def tanh_derivative(x): return 1 - np.tanh(x)**2

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

# Training data
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([
    [1,0,0], 
    [0,1,0], 
    [0,0,1], 
    [1,0,0]  
])

# Network architecture: input → hidden1 → hidden2 → output(3 classes)
layers = [2, 4, 3, 3]   
activations = ["relu", "tanh", "softmax"]
lr = 0.51
epochs = 10

# Initialize weights and biases
np.random.seed(42)
weights = [np.random.randn(layers[i], layers[i+1]) for i in range(len(layers)-1)]
biases  = [np.zeros((1, layers[i+1])) for i in range(len(layers)-1)]
# Training loop
for epoch in range(epochs):
    # Forward pass
    zs, activs = [], [X]
    for i in range(len(weights)):
        z = activs[-1].dot(weights[i]) + biases[i]
        zs.append(z)
        if activations[i] == "relu":
            a = relu(z)
        elif activations[i] == "tanh":
            a = tanh(z)
        elif activations[i] == "softmax":
            a = softmax(z)
        activs.append(a)

    # Error (target - output)
    error = y - activs[-1]

    # Backpropagation
    grads_w, grads_b = [None]*len(weights), [None]*len(biases)
    delta = error   # directly use error at output layer

    for i in reversed(range(len(weights))):
        grads_w[i] = activs[i].T.dot(delta)
        grads_b[i] = np.sum(delta, axis=0, keepdims=True)

        if i > 0:
            if activations[i-1] == "relu":
                delta = delta.dot(weights[i].T) * relu_derivative(zs[i-1])
            elif activations[i-1] == "tanh":
                delta = delta.dot(weights[i].T) * tanh_derivative(zs[i-1])

    # Update weights
    for i in range(len(weights)):
        weights[i] += lr * grads_w[i]   
        biases[i]  += lr * grads_b[i]

# Print final results
print(f"Total Epochs: {epochs}")
print("Final Derived Output:\n", activs[-1])
print("Final Error:\n", error)
for i, w in enumerate(weights):
    print(f"Final Updated Weights W{i+1}:\n", w)
for i, b in enumerate(biases):
    print(f"Final Updated Biases b{i+1}:\n", b)

Total Epochs: 10
Final Derived Output:
 [[0.7650729  0.05147043 0.18345666]
 [0.13389065 0.27911264 0.58699671]
 [0.13368908 0.27506614 0.59124478]
 [0.13317082 0.2751497  0.59167948]]
Final Error:
 [[ 0.2349271  -0.05147043 -0.18345666]
 [-0.13389065  0.72088736 -0.58699671]
 [-0.13368908 -0.27506614  0.40875522]
 [ 0.86682918 -0.2751497  -0.59167948]]
Final Updated Weights W1:
 [[ 1.76848671 -0.1382643   1.53115244  0.8862026 ]
 [-0.30779755 -0.23413696  1.91320359  0.66037018]]
Final Updated Weights W2:
 [[-0.44186613  1.67951226 -0.52657365]
 [-0.46572975  0.24196227 -1.91328024]
 [-2.10706653  1.27800469 -0.89583773]
 [-0.75460527  0.03765484 -1.38293522]]
Final Updated Weights W3:
 [[ 1.47417534 -0.75012162  0.58334695]
 [-0.50878255 -0.91360249 -0.43582328]
 [-1.18276933  0.08337301 -0.27653793]]
Final Updated Biases b1:
 [[-0.05853323  0.         -0.06595825 -0.77684629]]
Final Updated Biases b2:
 [[ 0.94104976  0.13420573 -0.64832877]]
Final Updated Biases b3:
 [[ 0.84361583 -